name: linux_serial
description: Dart package for accessing serial on Linux.
version: 0.0.1
author: Hannes Winkler
homepage: https://ardera.dev

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  ffi: ^0.1.3
  meta: ^1.1.8
  tuple: ^1.0.3
  path: ^1.7.0
  async: ^2.4.2
  computer: ^1.0.2
  synchronized: ^2.2.0+2